# Generated by Django 5.2.7 on 2025-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
